//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometProject.PageObject.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PayRollDetailsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayRollDetailsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CometProject.PageObject.Package.PayRollDetailsResource", typeof(PayRollDetailsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;wucButtons_cmdAddEnabled&apos;].
        /// </summary>
        internal static string PayRollDetailsPage_AddButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("PayRollDetailsPage_AddButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;Form1&apos;]/table/tbody/tr[2]/td/table/tbody/tr/td[5].
        /// </summary>
        internal static string PayRollDetailsPage_FormText_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("PayRollDetailsPage_FormText_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;divMenuddmPayCycleID&apos;]/table/tbody/tr[2]/td[1].
        /// </summary>
        internal static string PayRollDetailsPage_MenuPayCycleIdDropDown_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("PayRollDetailsPage_MenuPayCycleIdDropDown_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;ddmPayCycleID_trMain&apos;]/td[2]/img.
        /// </summary>
        internal static string PayRollDetailsPage_PayCycleIdDropDown_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("PayRollDetailsPage_PayCycleIdDropDown_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPayrollID.
        /// </summary>
        internal static string PayRollDetailsPage_PayRollIdText_SendKeys_XPath_Locator {
            get {
                return ResourceManager.GetString("PayRollDetailsPage_PayRollIdText_SendKeys_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtons_cmdSaveEnabled.
        /// </summary>
        internal static string PayRollDetailsPage_SaveButton_Click_Id_Locator {
            get {
                return ResourceManager.GetString("PayRollDetailsPage_SaveButton_Click_Id_Locator", resourceCulture);
            }
        }
    }
}
