//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Acceptance.Comet.Tests.PageObject.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmployeeDetailsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeDetailsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Acceptance.Comet.Tests.PageObject.Package.EmployeeDetailsResource", typeof(EmployeeDetailsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgEmployerLookup.
        /// </summary>
        internal static string EmployeeDetailsPage_EmployerLookupButton_Click_Id_Locator {
            get {
                return ResourceManager.GetString("EmployeeDetailsPage_EmployerLookupButton_Click_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;ddmEmployerOfferingID_trMain&apos;]/td[2]/img.
        /// </summary>
        internal static string EmployeeDetailsPage_EmployerOfferingIdDropDown_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("EmployeeDetailsPage_EmployerOfferingIdDropDown_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;Form1&apos;]/table/tbody/tr[2]/td/table/tbody/tr/td[4].
        /// </summary>
        internal static string EmployeeDetailsPage_FormText_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("EmployeeDetailsPage_FormText_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;divMenuddmEmployerOfferingID&apos;]/table/tbody/tr[2]/td[1].
        /// </summary>
        internal static string EmployeeDetailsPage_MenuEmployerOfferingIdDropDown_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("EmployeeDetailsPage_MenuEmployerOfferingIdDropDown_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;wucButtons_cmdNextEnabled&apos;]&quot;.
        /// </summary>
        internal static string EmployeeDetailsPage_NextButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("EmployeeDetailsPage_NextButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cboSetUpReason.
        /// </summary>
        internal static string EmployeeDetailsPage_SetupReasonDropDown_Select_Id_Locator {
            get {
                return ResourceManager.GetString("EmployeeDetailsPage_SetupReasonDropDown_Select_Id_Locator", resourceCulture);
            }
        }
    }
}
