//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLProject.Page_Object {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOLProject.Page_Object.TransactionResource", typeof(TransactionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[4]/a.
        /// </summary>
        internal static string TransactionPage_AdvanceFilterButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_AdvanceFilterButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (//span[@class=&apos;date-picker-container&apos;])[2]/img&quot;.
        /// </summary>
        internal static string TransactionPage_DatePickerCalenderButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_DatePickerCalenderButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;ui-datepicker-calendar&apos;]//tr//td/a[contains(text(),.
        /// </summary>
        internal static string TransactionPage_DatePickerCalenderTextButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_DatePickerCalenderTextButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (//span[@class=&apos;date-picker-container&apos;])[1]/img.
        /// </summary>
        internal static string TransactionPage_FromDateButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_FromDateButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@title=&apos;Prev&apos;].
        /// </summary>
        internal static string TransactionPage_PreviusButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_PreviusButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;main &apos;]/div[2]/div[1]/div/ul/li[1]/a/span[2].
        /// </summary>
        internal static string TransactionPage_ScrollBar_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_ScrollBar_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@id=&apos;submit-form&apos;].
        /// </summary>
        internal static string TransactionPage_SubmitButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_SubmitButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;transactions-table-0&apos;]/tbody/tr.
        /// </summary>
        internal static string TransactionPage_TransactionCountLabel_Count_XPath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_TransactionCountLabel_Count_XPath_Locator", resourceCulture);
            }
        }
    }
}
