//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROLProject.Page_Object {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ROLProject.Page_Object.ContactResource", typeof(ContactResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[2]/div[2]/div/div[1]/button.
        /// </summary>
        internal static string ContactPage_ChangeButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_ChangeButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[2]/div[2]/div/div[1]/div/ul/li[5]/a/span[.=&apos;Change deduction for a benefit in my package&apos;].
        /// </summary>
        internal static string ContactPage_ChangeButtonOption_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_ChangeButtonOption_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change-date-next.
        /// </summary>
        internal static string ContactPage_ChangeDateButton_Click_Id_Locator {
            get {
                return ResourceManager.GetString("ContactPage_ChangeDateButton_Click_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;contact&apos;]//h1/span.
        /// </summary>
        internal static string ContactPage_ContactPageHeader_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_ContactPageHeader_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[4]/div[2]/div/div[1]/button.
        /// </summary>
        internal static string ContactPage_CurrentBenefitButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_CurrentBenefitButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[4]/div[2]/div/div[1]/div/ul/li[2]/a/span[.=&apos;Administration Fee&apos;].
        /// </summary>
        internal static string ContactPage_CurrentBenefitButtonOption_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_CurrentBenefitButtonOption_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deduction-amount.
        /// </summary>
        internal static string ContactPage_DeductionAmountTextBox_SendKeys_Id_Locator {
            get {
                return ResourceManager.GetString("ContactPage_DeductionAmountTextBox_SendKeys_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ContactPage_EmailText_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_EmailText_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[2]/div[2]/div/div[1]/button.
        /// </summary>
        internal static string ContactPage_FromContactButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_FromContactButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[1]/div[2]/div/div[1]/button.
        /// </summary>
        internal static string ContactPage_IWantToDropDown_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_IWantToDropDown_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contactForm&apos;]/div[4]/div[1]/div[2]/div/div[1]/div/ul/li[2]/a/span[.=&apos;Make a change to my package&apos;].
        /// </summary>
        internal static string ContactPage_IWantToDropDownOption_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ContactPage_IWantToDropDownOption_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ContactPage_MessageTextBox_SendKeys_Id_Locator {
            get {
                return ResourceManager.GetString("ContactPage_MessageTextBox_SendKeys_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferred-phone.
        /// </summary>
        internal static string ContactPage_PhoneTextBox_SendKeys_Id_Locator {
            get {
                return ResourceManager.GetString("ContactPage_PhoneTextBox_SendKeys_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact-submit.
        /// </summary>
        internal static string ContactPage_SubmitButton_Click_Id_Locator {
            get {
                return ResourceManager.GetString("ContactPage_SubmitButton_Click_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;success-content&apos;].
        /// </summary>
        internal static string ContactPage_SubmitStatus_GetText_Id_Locator {
            get {
                return ResourceManager.GetString("ContactPage_SubmitStatus_GetText_Id_Locator", resourceCulture);
            }
        }
    }
}
