//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROLProject.Page_Object {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ROLProject.Page_Object.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /div[1]/div[2]/div[1]/a.
        /// </summary>
        internal static string DashboardPage_BenefitLabel_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("DashboardPage_BenefitLabel_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]//h1/span.
        /// </summary>
        internal static string DashboardPage_DashboardLabel_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("DashboardPage_DashboardLabel_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div[1]/div/div.
        /// </summary>
        internal static string DashboardPage_NumBenefitLabel_GetText_XPath_Locator {
            get {
                return ResourceManager.GetString("DashboardPage_NumBenefitLabel_GetText_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardPage_PageTitle_Title_Value {
            get {
                return ResourceManager.GetString("DashboardPage_PageTitle_Title_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;login&apos;]/div[5]/div/ul/li.
        /// </summary>
        internal static string DashboardPage_ScrollBar_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("DashboardPage_ScrollBar_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;View payroll deductions &amp; transfers&apos;)].
        /// </summary>
        internal static string DashboardPage_ViewPayrollDeductionTransactionButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("DashboardPage_ViewPayrollDeductionTransactionButton_Click_XPath_Locator", resourceCulture);
            }
        }
    }
}
