//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CallCentreEnquiryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CallCentreEnquiryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.CallCentreEnquiryResource", typeof(CallCentreEnquiryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments.
        /// </summary>
        internal static string CallCentreEnquiry_Amendment_LinkText_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Amendment_LinkText_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgBanner.
        /// </summary>
        internal static string CallCentreEnquiry_ApplictionLogo_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ApplictionLogo_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        internal static string CallCentreEnquiry_Benifit_LinkText_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Benifit_LinkText_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Package.
        /// </summary>
        internal static string CallCentreEnquiry_CreatePackage_LinkText_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_CreatePackage_LinkText_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdEmail.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeEmail_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeEmail_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdGender.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeGender_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeGender_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdEmployeeName.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeName_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdEmployeeNo.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeNumber_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeNumber_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtEmployeeNumber.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeNumberTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeNumberTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtEmployerCode.
        /// </summary>
        internal static string CallCentreEnquiry_EmployerCodeTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployerCodeTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_cmdNew.
        /// </summary>
        internal static string CallCentreEnquiry_NewButton_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_NewButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet2.
        /// </summary>
        internal static string CallCentreEnquiry_PackageNameWithEmployeeNumber_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_PackageNameWithEmployeeNumber_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet3.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenu_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenu_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu10.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_AdminFrees_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_AdminFrees_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu2.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_Edit_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_Edit_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu5.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_ReviewAndActivate_Locator1 {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_ReviewAndActivate_Locator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_cmdSearch.
        /// </summary>
        internal static string CallCentreEnquiry_SearchButton_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_SearchButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtSurname.
        /// </summary>
        internal static string CallCentreEnquiry_SurnametextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_SurnametextBox_Id_Locator", resourceCulture);
            }
        }
    }
}
